name: localconnect
description: A new Flutter project.
publish_to: 'none' 
version: 1.3.0+2

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # json_rpc_2: ^3.0.2
  # web_socket_channel: ^2.4.0
  # simple_peer: ^0.0.13
  # peerdart: ^0.5.3
  
  network_discovery: ^1.0.0
  device_info_plus: ^9.0.3
  flutter_riverpod: ^2.4.0
  shared_preferences: ^2.2.1
  flutter_markdown: ^0.6.17+3
  flutter_colorpicker: ^1.0.3
  url_launcher: ^6.1.14
  adaptive_theme: ^3.4.0
  toggle_switch: ^2.1.0
  flutter_native_splash: ^2.3.2
  salomon_bottom_bar: ^3.3.2
  # udp: ^5.0.3

  file_selector: ^1.0.1
  image_picker: ^1.0.4
  http: ^1.1.0
  # filesystem_picker: ^3.1.0
  file_picker: ^5.5.0
  path_provider: ^2.1.1

  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: fd519be1e8398c6b6c2062c2447bac960a71bc02

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  # change_app_package_name: ^1.1.0
  # rename_app: ^1.1.0
  # flutter_app_name: ^0.1.1
  # rename: ^2.1.1
  msix: ^3.16.2
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/logo-mob.png

  fonts:
    - family: Custom
      fonts:
        - asset: assets/custom.ttf
      
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

# flutter_app_name:
#   name: "LocalConnect"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo-mob.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_foreground: "assets/logo-mob.png"
  adaptive_icon_background: "#FF5722"
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 256
  macos:
    generate: true
    image_path: "assets/logo.png"

msix_config:
  display_name: LocalConnect
  publisher_display_name: Bipin
  publisher: Bipin
  identity_name: com.bipin.localconnect
  logo_path: assets/logo.png
  os_min_version: 10.0.19041.0
  # install_certificate: false
  # sign_msix: false
  startup_task:
    task_id: localconnect
    enabled: false
    parameters: autostart

flutter_native_splash:
  color: "#FF5722"
  image: "assets/logo.png"

  android_12:
    image: "assets/logo-mob.png"
    icon_background_color: "#FF5722"